table base_paper_reference
	lineageTag: e4f5a6b7-c8d9-0123-defa-234567890123

	column barrier_type
		dataType: string
		sourceColumn: barrier_type
		summarizeBy: none

	column description
		dataType: string
		sourceColumn: description
		summarizeBy: none

	column base_paper_rate
		dataType: double
		sourceColumn: base_paper_rate
		summarizeBy: none

	column barrierlens_observed
		dataType: double
		sourceColumn: barrierlens_observed
		summarizeBy: none

	column barrierlens_predicted
		dataType: double
		sourceColumn: barrierlens_predicted
		summarizeBy: none

	column base_paper_n
		dataType: string
		sourceColumn: base_paper_n
		summarizeBy: none

	column barrierlens_n
		dataType: string
		sourceColumn: barrierlens_n
		summarizeBy: none

	column source_note
		dataType: string
		sourceColumn: source_note
		summarizeBy: none

	column comparability
		dataType: string
		sourceColumn: comparability
		summarizeBy: none

	partition base_paper_reference = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/base_paper_reference.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"barrier_type", type text}, {"description", type text}, {"base_paper_rate", type number}, {"barrierlens_observed", type number}, {"barrierlens_predicted", type number}, {"base_paper_n", type text}, {"barrierlens_n", type text}, {"source_note", type text}, {"comparability", type text}})
			in
				#"Changed Type"
