table base_paper_barrier_long
	lineageTag: 0c809670-9899-45d3-819e-f0d5ab60ad08

	column barrier_type
		dataType: string
		sourceColumn: barrier_type
		summarizeBy: none

	column comparison_source
		dataType: string
		sourceColumn: comparison_source
		summarizeBy: none

	column value
		dataType: double
		sourceColumn: value
		summarizeBy: none

	partition base_paper_barrier_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/base_paper_barrier_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

