table classification_report_display
	lineageTag: aee24f98-87f4-4f69-8b2f-bbc6e8877d87

	column model
		dataType: string
		sourceColumn: model
		summarizeBy: none

	column target
		dataType: string
		sourceColumn: target
		summarizeBy: none

	column class
		dataType: string
		sourceColumn: class
		summarizeBy: none

	column class_display
		dataType: string
		sourceColumn: class_display
		summarizeBy: none

	column precision
		dataType: double
		sourceColumn: precision
		summarizeBy: none

	column recall
		dataType: double
		sourceColumn: recall
		summarizeBy: none

	column f1-score
		dataType: double
		sourceColumn: f1-score
		summarizeBy: none

	column support
		dataType: double
		sourceColumn: support
		summarizeBy: none

	partition classification_report_display = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/classification_report_display.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

