table cluster_summary
	lineageTag: f9eec559-f8c8-462d-a1ea-04687d139b3b

	column cluster_id
		dataType: int64
		sourceColumn: cluster_id
		summarizeBy: none

	column archetype_name
		dataType: string
		sourceColumn: archetype_name
		summarizeBy: none

	column n_women
		dataType: int64
		sourceColumn: n_women
		summarizeBy: none

	column share_of_total
		dataType: double
		sourceColumn: share_of_total
		summarizeBy: none

	column media_exposure_index_mean
		dataType: double
		sourceColumn: media_exposure_index_mean
		summarizeBy: none

	column digital_inclusion_index_mean
		dataType: double
		sourceColumn: digital_inclusion_index_mean
		summarizeBy: none

	column vulnerability_score_mean
		dataType: double
		sourceColumn: vulnerability_score_mean
		summarizeBy: none

	column pred_household_prob_mean
		dataType: double
		sourceColumn: pred_household_prob_mean
		summarizeBy: none

	column pred_logistic_prob_mean
		dataType: double
		sourceColumn: pred_logistic_prob_mean
		summarizeBy: none

	column pred_facility_prob_mean
		dataType: double
		sourceColumn: pred_facility_prob_mean
		summarizeBy: none

	column composite_barrier_score_mean
		dataType: double
		sourceColumn: composite_barrier_score_mean
		summarizeBy: none

	column risk_tier
		dataType: string
		sourceColumn: risk_tier
		summarizeBy: none

	partition cluster_summary = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/cluster_summary.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

