table cluster_radar_long
	lineageTag: 1cf6cf3d-5d95-44c1-9e5f-55dd74058774

	column cluster_id
		dataType: int64
		sourceColumn: cluster_id
		summarizeBy: none

	column archetype_name
		dataType: string
		sourceColumn: archetype_name
		summarizeBy: none

	column risk_tier
		dataType: string
		sourceColumn: risk_tier
		summarizeBy: none

	column metric_label
		dataType: string
		sourceColumn: metric_label
		summarizeBy: none

	column value
		dataType: double
		sourceColumn: value
		summarizeBy: none

	partition cluster_radar_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/cluster_radar_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

