table cluster_state_distribution
	lineageTag: 9f0389d4-247e-4c96-bc8c-dd9994780420

	column cluster_id
		dataType: int64
		sourceColumn: cluster_id
		summarizeBy: none

	column archetype_name
		dataType: string
		sourceColumn: archetype_name
		summarizeBy: none

	column state_name
		dataType: string
		sourceColumn: state_name
		summarizeBy: none

	column n_women
		dataType: int64
		sourceColumn: n_women
		summarizeBy: none

	column share_within_cluster
		dataType: double
		sourceColumn: share_within_cluster
		summarizeBy: none

	partition cluster_state_distribution = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/cluster_state_distribution.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"cluster_id", Int64.Type}, {"archetype_name", type text}, {"state_name", type text}, {"n_women", Int64.Type}, {"share_within_cluster", type number}})
			in
				#"Changed Type"

