table cluster_state_distribution
	lineageTag: 558cc34c-e0d6-4796-9597-036af1981906

	column cluster_id
		dataType: int64
		sourceColumn: cluster_id
		summarizeBy: none

	column archetype_name
		dataType: string
		sourceColumn: archetype_name
		summarizeBy: none

	column state_name
		dataType: string
		sourceColumn: state_name
		summarizeBy: none

	column n_women
		dataType: int64
		sourceColumn: n_women
		summarizeBy: none

	column share_within_cluster
		dataType: double
		sourceColumn: share_within_cluster
		summarizeBy: none

	column risk_tier
		dataType: string
		sourceColumn: risk_tier
		summarizeBy: none

	partition cluster_state_distribution = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/cluster_state_distribution.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

