table demographic_summary
	lineageTag: 1e809263-e6d8-4b87-9d20-883342909cc9

	column wealth_tier
		dataType: string
		sourceColumn: wealth_tier
		summarizeBy: none

	column education_tier
		dataType: string
		sourceColumn: education_tier
		summarizeBy: none

	column residence
		dataType: string
		sourceColumn: residence
		summarizeBy: none

	column caste_group
		dataType: string
		sourceColumn: caste_group
		summarizeBy: none

	column barrier_type
		dataType: string
		sourceColumn: barrier_type
		summarizeBy: none

	column N
		dataType: int64
		sourceColumn: N
		summarizeBy: none

	column suppress_flag
		dataType: boolean
		sourceColumn: suppress_flag
		summarizeBy: none

	column mean_observed_rate
		dataType: double
		sourceColumn: mean_observed_rate
		summarizeBy: none

	column mean_predicted_prob
		dataType: double
		sourceColumn: mean_predicted_prob
		summarizeBy: none

	column data_rail_observed
		dataType: string
		sourceColumn: data_rail_observed
		summarizeBy: none

	column data_rail_predicted
		dataType: string
		sourceColumn: data_rail_predicted
		summarizeBy: none

	partition demographic_summary = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/demographic_summary.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

