table demographic_comparison_long
	lineageTag: 60038384-57fb-41bb-b92f-59ef9ac4d343

	column wealth_tier
		dataType: string
		sourceColumn: wealth_tier
		summarizeBy: none

	column education_tier
		dataType: string
		sourceColumn: education_tier
		summarizeBy: none

	column residence
		dataType: string
		sourceColumn: residence
		summarizeBy: none

	column caste_group
		dataType: string
		sourceColumn: caste_group
		summarizeBy: none

	column barrier_type
		dataType: string
		sourceColumn: barrier_type
		summarizeBy: none

	column N
		dataType: int64
		sourceColumn: N
		summarizeBy: none

	column demographic_cell
		dataType: string
		sourceColumn: demographic_cell
		summarizeBy: none

	column metric_type
		dataType: string
		sourceColumn: metric_type
		summarizeBy: none

	column value
		dataType: double
		sourceColumn: value
		summarizeBy: none

	column data_rail
		dataType: string
		sourceColumn: data_rail
		summarizeBy: none

	partition demographic_comparison_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/demographic_comparison_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

