table demographic_caste_long
	lineageTag: f15ec399-7b0f-47cc-aede-e1f6beecaf94

	column category
		dataType: string
		sourceColumn: category
		summarizeBy: none

	column metric_type
		dataType: string
		sourceColumn: metric_type
		summarizeBy: none

	column value
		dataType: double
		sourceColumn: value
		summarizeBy: none

	column N
		dataType: int64
		sourceColumn: N
		summarizeBy: none

	partition demographic_caste_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/demographic_caste_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

