table demographic_residence_long
	lineageTag: 22924b9e-e47f-445b-a17b-90ca729d27b2

	column category
		dataType: string
		sourceColumn: category
		summarizeBy: none

	column metric_type
		dataType: string
		sourceColumn: metric_type
		summarizeBy: none

	column value
		dataType: double
		sourceColumn: value
		summarizeBy: none

	column N
		dataType: int64
		sourceColumn: N
		summarizeBy: none

	partition demographic_residence_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/demographic_residence_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

