table hyperparameters_display
	lineageTag: b783d28d-bb90-4f8c-b8dd-bc83103f8e58

	column parameter
		dataType: string
		sourceColumn: parameter
		summarizeBy: none

	column value
		dataType: string
		sourceColumn: value
		summarizeBy: none

	column parameter_code
		dataType: string
		sourceColumn: parameter_code
		summarizeBy: none

	partition hyperparameters_display = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/hyperparameters_display.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

