table hyperparameters_display
	lineageTag: a6b7c8d9-e0f1-2345-fabc-456789012345

	column parameter
		dataType: string
		sourceColumn: parameter
		summarizeBy: none

	column value
		dataType: string
		sourceColumn: value
		summarizeBy: none

	column parameter_code
		dataType: string
		sourceColumn: parameter_code
		summarizeBy: none

	partition hyperparameters_display = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/hyperparameters_display.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"parameter", type text}, {"value", type text}, {"parameter_code", type text}})
			in
				#"Changed Type"
