table model_comparison_table
	lineageTag: 6a0e56fa-bace-4a8a-9335-2940d134a024

	column Model
		dataType: string
		sourceColumn: Model
		summarizeBy: none

	column Target
		dataType: string
		sourceColumn: Target
		summarizeBy: none

	column Accuracy
		dataType: double
		sourceColumn: Accuracy
		summarizeBy: none

	column 'ROC-AUC'
		dataType: double
		sourceColumn: 'ROC-AUC'
		summarizeBy: none

	column Precision
		dataType: double
		sourceColumn: Precision
		summarizeBy: none

	column Recall
		dataType: double
		sourceColumn: Recall
		summarizeBy: none

	column 'F1-Score'
		dataType: double
		sourceColumn: 'F1-Score'
		summarizeBy: none

	column 'Baseline_ROC-AUC'
		dataType: double
		sourceColumn: 'Baseline_ROC-AUC'
		summarizeBy: none

	column 'Full_ROC-AUC'
		dataType: double
		sourceColumn: 'Full_ROC-AUC'
		summarizeBy: none

	column Barrier_Uplift
		dataType: double
		sourceColumn: Barrier_Uplift
		summarizeBy: none

	partition model_comparison_table = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/model_comparison_table.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Model", type text}, {"Target", type text}, {"Accuracy", type number}, {#"ROC-AUC", type number}, {"Precision", type number}, {"Recall", type number}, {#"F1-Score", type number}, {#"Baseline_ROC-AUC", type number}, {#"Full_ROC-AUC", type number}, {"Barrier_Uplift", type number}})
			in
				#"Changed Type"

