table model_comparison_table
	lineageTag: 3ca406f9-6bfa-49b6-a454-2a20a1a64713

	column Model
		dataType: string
		sourceColumn: Model
		summarizeBy: none

	column Target
		dataType: string
		sourceColumn: Target
		summarizeBy: none

	column Accuracy
		dataType: double
		sourceColumn: Accuracy
		summarizeBy: none

	column ROC-AUC
		dataType: double
		sourceColumn: ROC-AUC
		summarizeBy: none

	column Precision
		dataType: double
		sourceColumn: Precision
		summarizeBy: none

	column Recall
		dataType: double
		sourceColumn: Recall
		summarizeBy: none

	column F1-Score
		dataType: double
		sourceColumn: F1-Score
		summarizeBy: none

	column Baseline_ROC-AUC
		dataType: double
		sourceColumn: Baseline_ROC-AUC
		summarizeBy: none

	column Full_ROC-AUC
		dataType: double
		sourceColumn: Full_ROC-AUC
		summarizeBy: none

	column Barrier_Uplift
		dataType: double
		sourceColumn: Barrier_Uplift
		summarizeBy: none

	partition model_comparison_table = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/model_comparison_table.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

