table national_barrier_predicted_mix
	lineageTag: de141c3c-4014-4e56-925e-f178bb34f698

	column barrier_type
		dataType: string
		sourceColumn: barrier_type
		summarizeBy: none

	column value
		dataType: double
		sourceColumn: value
		summarizeBy: none

	column share
		dataType: double
		sourceColumn: share
		summarizeBy: none

	partition national_barrier_predicted_mix = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/national_barrier_predicted_mix.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

