table national_barrier_long
	lineageTag: 50586cb2-8f04-4e37-becb-5d38f2244ffb

	column barrier_type
		dataType: string
		sourceColumn: barrier_type
		summarizeBy: none

	column metric_type
		dataType: string
		sourceColumn: metric_type
		summarizeBy: none

	column value
		dataType: double
		sourceColumn: value
		summarizeBy: none

	column data_rail
		dataType: string
		sourceColumn: data_rail
		summarizeBy: none

	partition national_barrier_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/national_barrier_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

