table national_kpi_summary
	lineageTag: 400e4633-c923-4358-8437-4c9ac8866b0b

	column total_women
		dataType: int64
		sourceColumn: total_women
		summarizeBy: none

	column observed_any_barrier_rate
		dataType: double
		sourceColumn: observed_any_barrier_rate
		summarizeBy: none

	column observed_household_rate
		dataType: double
		sourceColumn: observed_household_rate
		summarizeBy: none

	column observed_logistic_rate
		dataType: double
		sourceColumn: observed_logistic_rate
		summarizeBy: none

	column observed_facility_rate
		dataType: double
		sourceColumn: observed_facility_rate
		summarizeBy: none

	column pred_household_prob
		dataType: double
		sourceColumn: pred_household_prob
		summarizeBy: none

	column pred_logistic_prob
		dataType: double
		sourceColumn: pred_logistic_prob
		summarizeBy: none

	column pred_facility_prob
		dataType: double
		sourceColumn: pred_facility_prob
		summarizeBy: none

	column pred_composite_barrier_score
		dataType: double
		sourceColumn: pred_composite_barrier_score
		summarizeBy: none

	column stage2_unmet_fp_N
		dataType: int64
		sourceColumn: stage2_unmet_fp_N
		summarizeBy: none

	column stage2_unmet_fp_observed_rate
		dataType: double
		sourceColumn: stage2_unmet_fp_observed_rate
		summarizeBy: none

	column stage2_unmet_fp_pred_prob
		dataType: double
		sourceColumn: stage2_unmet_fp_pred_prob
		summarizeBy: none

	column stage2_anc_gap_N
		dataType: int64
		sourceColumn: stage2_anc_gap_N
		summarizeBy: none

	column data_note
		dataType: string
		sourceColumn: data_note
		summarizeBy: none

	partition national_kpi_summary = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/national_kpi_summary.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"total_women", Int64.Type}, {"observed_any_barrier_rate", type number}, {"observed_household_rate", type number}, {"observed_logistic_rate", type number}, {"observed_facility_rate", type number}, {"pred_household_prob", type number}, {"pred_logistic_prob", type number}, {"pred_facility_prob", type number}, {"pred_composite_barrier_score", type number}, {"stage2_unmet_fp_N", Int64.Type}, {"stage2_unmet_fp_observed_rate", type number}, {"stage2_unmet_fp_pred_prob", type number}, {"stage2_anc_gap_N", Int64.Type}, {"data_note", type text}})
			in
				#"Changed Type"

