table shap_importance
	lineageTag: 56dc6dae-1358-4a74-9eaa-9ec52f5c7947

	column model
		dataType: string
		sourceColumn: model
		summarizeBy: none

	column target
		dataType: string
		sourceColumn: target
		summarizeBy: none

	column rank
		dataType: int64
		sourceColumn: rank
		summarizeBy: none

	column feature
		dataType: string
		sourceColumn: feature
		summarizeBy: none

	column mean_abs_shap
		dataType: double
		sourceColumn: mean_abs_shap
		summarizeBy: none

	partition shap_importance = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/shap_importance.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

