table shap_top20
	lineageTag: b1c2d3e4-f5a6-7890-abcd-ef1234567890

	column model
		dataType: string
		sourceColumn: model
		summarizeBy: none

	column target
		dataType: string
		sourceColumn: target
		summarizeBy: none

	column rank
		dataType: int64
		sourceColumn: rank
		summarizeBy: none

	column feature
		dataType: string
		sourceColumn: feature
		summarizeBy: none

	column mean_abs_shap
		dataType: double
		sourceColumn: mean_abs_shap
		summarizeBy: none

	partition shap_top20 = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/shap_top20.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"model", type text}, {"target", type text}, {"rank", Int64.Type}, {"feature", type text}, {"mean_abs_shap", type number}})
			in
				#"Changed Type"
