table shap_top20
	lineageTag: de2e404d-4b8e-4601-a3ac-3255c1e2460f

	column model
		dataType: string
		sourceColumn: model
		summarizeBy: none

	column target
		dataType: string
		sourceColumn: target
		summarizeBy: none

	column rank
		dataType: int64
		sourceColumn: rank
		summarizeBy: none

	column feature
		dataType: string
		sourceColumn: feature
		summarizeBy: none

	column mean_abs_shap
		dataType: double
		sourceColumn: mean_abs_shap
		summarizeBy: none

	partition shap_top20 = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/shap_top20.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

