table shap_importance
	lineageTag: a3f1c820-7d4e-4b19-b2c8-9e5f1d2a3c4b

	column model
		dataType: string
		sourceColumn: model
		summarizeBy: none

	column target
		dataType: string
		sourceColumn: target
		summarizeBy: none

	column rank
		dataType: int64
		sourceColumn: rank
		summarizeBy: none

	column feature
		dataType: string
		sourceColumn: feature
		summarizeBy: none

	column mean_abs_shap
		dataType: double
		sourceColumn: mean_abs_shap
		summarizeBy: none

	partition shap_importance = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/shap_importance.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"model", type text}, {"target", type text}, {"rank", Int64.Type}, {"feature", type text}, {"mean_abs_shap", type number}})
			in
				#"Changed Type"
