table stage2_outcome_long
	lineageTag: caca5450-0f34-48e7-b8ed-5217d12e38f0

	column granularity
		dataType: string
		sourceColumn: granularity
		summarizeBy: none

	column state_name
		dataType: string
		sourceColumn: state_name
		summarizeBy: none

	column outcome
		dataType: string
		sourceColumn: outcome
		summarizeBy: none

	column metric_type
		dataType: string
		sourceColumn: metric_type
		summarizeBy: none

	column value
		dataType: double
		sourceColumn: value
		summarizeBy: none

	column N
		dataType: int64
		sourceColumn: N
		summarizeBy: none

	partition stage2_outcome_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/stage2_outcome_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

