table stage1_model_comparison
	lineageTag: a8a04269-ab41-4482-96c4-15906347e27e

	column Model
		dataType: string
		sourceColumn: Model
		summarizeBy: none

	column Target
		dataType: string
		sourceColumn: Target
		summarizeBy: none

	column Accuracy
		dataType: double
		sourceColumn: Accuracy
		summarizeBy: none

	column ROC-AUC
		dataType: double
		sourceColumn: ROC-AUC
		summarizeBy: none

	column Precision
		dataType: double
		sourceColumn: Precision
		summarizeBy: none

	column Recall
		dataType: double
		sourceColumn: Recall
		summarizeBy: none

	column F1-Score
		dataType: double
		sourceColumn: F1-Score
		summarizeBy: none

	partition stage1_model_comparison = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/stage1_model_comparison.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

