table stage2_xgboost_results
	lineageTag: 5d58da1a-476a-4493-9166-273e72ae35bc

	column Model
		dataType: string
		sourceColumn: Model
		summarizeBy: none

	column Target
		dataType: string
		sourceColumn: Target
		summarizeBy: none

	column Accuracy
		dataType: double
		sourceColumn: Accuracy
		summarizeBy: none

	column ROC-AUC
		dataType: double
		sourceColumn: ROC-AUC
		summarizeBy: none

	column Precision
		dataType: double
		sourceColumn: Precision
		summarizeBy: none

	column Recall
		dataType: double
		sourceColumn: Recall
		summarizeBy: none

	column F1-Score
		dataType: double
		sourceColumn: F1-Score
		summarizeBy: none

	column TrainSize
		dataType: int64
		sourceColumn: TrainSize
		summarizeBy: none

	column TestSize
		dataType: int64
		sourceColumn: TestSize
		summarizeBy: none

	column PositiveRate
		dataType: double
		sourceColumn: PositiveRate
		summarizeBy: none

	column param_max_depth
		dataType: int64
		sourceColumn: param_max_depth
		summarizeBy: none

	column param_n_estimators
		dataType: int64
		sourceColumn: param_n_estimators
		summarizeBy: none

	column CV_ROC-AUC
		dataType: double
		sourceColumn: CV_ROC-AUC
		summarizeBy: none

	column Baseline_ROC-AUC
		dataType: double
		sourceColumn: Baseline_ROC-AUC
		summarizeBy: none

	column Full_ROC-AUC
		dataType: double
		sourceColumn: Full_ROC-AUC
		summarizeBy: none

	column Barrier_Uplift
		dataType: double
		sourceColumn: Barrier_Uplift
		summarizeBy: none

	partition stage2_xgboost_results = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/stage2_xgboost_results.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

