table stage1_barrier_rates_long
	lineageTag: c71bc34e-2ef5-408d-b850-83f06e581fd5

	column model
		dataType: string
		sourceColumn: model
		summarizeBy: none

	column barrier_type
		dataType: string
		sourceColumn: barrier_type
		summarizeBy: none

	column accuracy
		dataType: double
		sourceColumn: accuracy
		summarizeBy: none

	column roc_auc
		dataType: double
		sourceColumn: roc_auc
		summarizeBy: none

	column f1_score
		dataType: double
		sourceColumn: f1_score
		summarizeBy: none

	column precision
		dataType: double
		sourceColumn: precision
		summarizeBy: none

	column recall
		dataType: double
		sourceColumn: recall
		summarizeBy: none

	partition stage1_barrier_rates_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/stage1_barrier_rates_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

