table state_bottom10_long
	lineageTag: e2cbb026-938d-4ee2-8697-2fbb3c6983e5

	column rank_order
		dataType: int64
		sourceColumn: rank_order
		summarizeBy: none

	column state_name
		dataType: string
		sourceColumn: state_name
		summarizeBy: none

	column pred_composite_barrier_score
		dataType: double
		sourceColumn: pred_composite_barrier_score
		summarizeBy: none

	column N
		dataType: int64
		sourceColumn: N
		summarizeBy: none

	partition state_bottom10_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/state_bottom10_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

