table state_level_summary
	lineageTag: b8b3af06-6180-4e33-9936-d169058b8a83

	column state_name
		dataType: string
		sourceColumn: state_name
		summarizeBy: none

	column N
		dataType: int64
		sourceColumn: N
		summarizeBy: none

	column observed_household_rate
		dataType: double
		sourceColumn: observed_household_rate
		summarizeBy: none

	column pred_household_prob
		dataType: double
		sourceColumn: pred_household_prob
		summarizeBy: none

	column observed_logistic_rate
		dataType: double
		sourceColumn: observed_logistic_rate
		summarizeBy: none

	column pred_logistic_prob
		dataType: double
		sourceColumn: pred_logistic_prob
		summarizeBy: none

	column observed_facility_rate
		dataType: double
		sourceColumn: observed_facility_rate
		summarizeBy: none

	column pred_facility_prob
		dataType: double
		sourceColumn: pred_facility_prob
		summarizeBy: none

	column pred_composite_barrier_score
		dataType: double
		sourceColumn: pred_composite_barrier_score
		summarizeBy: none

	column cluster_0_share
		dataType: double
		sourceColumn: cluster_0_share
		summarizeBy: none

	column cluster_1_share
		dataType: double
		sourceColumn: cluster_1_share
		summarizeBy: none

	column target_unmet_fp_N
		dataType: int64
		sourceColumn: target_unmet_fp_N
		summarizeBy: none

	column target_unmet_fp_observed_rate
		dataType: double
		sourceColumn: target_unmet_fp_observed_rate
		summarizeBy: none

	column target_unmet_fp_pred_prob
		dataType: double
		sourceColumn: target_unmet_fp_pred_prob
		summarizeBy: none

	column target_anc_gap_N
		dataType: int64
		sourceColumn: target_anc_gap_N
		summarizeBy: none

	column target_anc_gap_observed_rate
		dataType: string
		sourceColumn: target_anc_gap_observed_rate
		summarizeBy: none

	column target_anc_gap_pred_prob
		dataType: string
		sourceColumn: target_anc_gap_pred_prob
		summarizeBy: none

	partition state_level_summary = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/state_level_summary.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"state_name", type text}, {"N", Int64.Type}, {"observed_household_rate", type number}, {"pred_household_prob", type number}, {"observed_logistic_rate", type number}, {"pred_logistic_prob", type number}, {"observed_facility_rate", type number}, {"pred_facility_prob", type number}, {"pred_composite_barrier_score", type number}, {"cluster_0_share", type number}, {"cluster_1_share", type number}, {"target_unmet_fp_N", Int64.Type}, {"target_unmet_fp_observed_rate", type number}, {"target_unmet_fp_pred_prob", type number}, {"target_anc_gap_N", Int64.Type}, {"target_anc_gap_observed_rate", type text}, {"target_anc_gap_pred_prob", type text}})
			in
				#"Changed Type"

