table state_ranking_long
	lineageTag: 43325925-fe7b-4d9b-b160-29ccd0a67e12

	column ranking_type
		dataType: string
		sourceColumn: ranking_type
		summarizeBy: none

	column rank_order
		dataType: int64
		sourceColumn: rank_order
		summarizeBy: none

	column state_name
		dataType: string
		sourceColumn: state_name
		summarizeBy: none

	column pred_composite_barrier_score
		dataType: double
		sourceColumn: pred_composite_barrier_score
		summarizeBy: none

	column N
		dataType: int64
		sourceColumn: N
		summarizeBy: none

	partition state_ranking_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/state_ranking_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

