table state_top10_long
	lineageTag: 71872834-fe92-4eae-9dc0-036ecfc5f8d3

	column rank_order
		dataType: int64
		sourceColumn: rank_order
		summarizeBy: none

	column state_name
		dataType: string
		sourceColumn: state_name
		summarizeBy: none

	column pred_composite_barrier_score
		dataType: double
		sourceColumn: pred_composite_barrier_score
		summarizeBy: none

	column N
		dataType: int64
		sourceColumn: N
		summarizeBy: none

	partition state_top10_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/state_top10_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

