table state_barrier_long
	lineageTag: 2ccc39ec-a8a8-453d-937c-da07924cc1c3

	column state_name
		dataType: string
		sourceColumn: state_name
		summarizeBy: none

	column barrier_type
		dataType: string
		sourceColumn: barrier_type
		summarizeBy: none

	column N
		dataType: int64
		sourceColumn: N
		summarizeBy: none

	column mean_observed_rate
		dataType: double
		sourceColumn: mean_observed_rate
		summarizeBy: none

	column mean_predicted_prob
		dataType: double
		sourceColumn: mean_predicted_prob
		summarizeBy: none

	column data_rail_observed
		dataType: string
		sourceColumn: data_rail_observed
		summarizeBy: none

	column data_rail_predicted
		dataType: string
		sourceColumn: data_rail_predicted
		summarizeBy: none

	partition state_barrier_long = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardDataPath & "/state_barrier_long.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

