table woman_level_master
	lineageTag: ea1c95fe-f967-492b-9ed4-61526ee4cb6f

	column woman_index
		dataType: int64
		sourceColumn: woman_index
		summarizeBy: none

	column caseid
		dataType: string
		sourceColumn: caseid
		summarizeBy: none

	column state_name
		dataType: string
		sourceColumn: state_name
		summarizeBy: none

	column residence
		dataType: string
		sourceColumn: residence
		summarizeBy: none

	column wealth_quintile
		dataType: string
		sourceColumn: wealth_quintile
		summarizeBy: none

	column wealth_tier
		dataType: string
		sourceColumn: wealth_tier
		summarizeBy: none

	column education_tier
		dataType: string
		sourceColumn: education_tier
		summarizeBy: none

	column caste_group
		dataType: string
		sourceColumn: caste_group
		summarizeBy: none

	column religion
		dataType: string
		sourceColumn: religion
		summarizeBy: none

	column occupation_group
		dataType: string
		sourceColumn: occupation_group
		summarizeBy: none

	column observed_household
		dataType: int64
		sourceColumn: observed_household
		summarizeBy: none

	column observed_logistic
		dataType: int64
		sourceColumn: observed_logistic
		summarizeBy: none

	column observed_facility
		dataType: int64
		sourceColumn: observed_facility
		summarizeBy: none

	column pred_household_prob
		dataType: double
		sourceColumn: pred_household_prob
		summarizeBy: none

	column pred_logistic_prob
		dataType: double
		sourceColumn: pred_logistic_prob
		summarizeBy: none

	column pred_facility_prob
		dataType: double
		sourceColumn: pred_facility_prob
		summarizeBy: none

	column composite_barrier_score
		dataType: double
		sourceColumn: composite_barrier_score
		summarizeBy: none

	column cluster_id
		dataType: int64
		sourceColumn: cluster_id
		summarizeBy: none

	column archetype_name
		dataType: string
		sourceColumn: archetype_name
		summarizeBy: none

	column observed_target_unmet_fp
		dataType: double
		sourceColumn: observed_target_unmet_fp
		summarizeBy: none

	column pred_target_unmet_fp_prob
		dataType: double
		sourceColumn: pred_target_unmet_fp_prob
		summarizeBy: none

	column observed_target_anc_gap
		dataType: string
		sourceColumn: observed_target_anc_gap
		summarizeBy: none

	column pred_target_anc_gap_prob
		dataType: string
		sourceColumn: pred_target_anc_gap_prob
		summarizeBy: none

	column media_exposure_index
		dataType: double
		sourceColumn: media_exposure_index
		summarizeBy: none

	column digital_inclusion_index
		dataType: double
		sourceColumn: digital_inclusion_index
		summarizeBy: none

	column vulnerability_score
		dataType: double
		sourceColumn: vulnerability_score
		summarizeBy: none

	partition woman_level_master = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents(DashboardMasterPath & "/woman_level_master.csv"),
					[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {}, "en-US")
			in
				#"Promoted Headers"

