"""Orchestrate dashboard dataset generation, validation, and export."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict

import pandas as pd

from src.dashboard.aggregations import (
    build_cluster_state_distribution,
    build_cluster_summary,
    build_demographic_summary,
    build_state_barrier_long,
    build_state_level_summary,
)
from src.dashboard.constants import (
    CLUSTER_STATE_OUTPUT,
    CLUSTER_SUMMARY_OUTPUT,
    DASHBOARD_DIR,
    DATA_DICTIONARY_OUTPUT,
    DEMO_SUMMARY_OUTPUT,
    MASTER_OUTPUT,
    MIN_CELL_N,
    PRED_COLS,
    STATE_BARRIER_LONG_OUTPUT,
    STATE_SUMMARY_OUTPUT,
    VALIDATION_REPORT_OUTPUT,
)
from src.dashboard.master import build_master_dataset, save_master_dataset
from src.dashboard.validation import (
    ValidationReport,
    validate_cluster_coverage,
    validate_demographic_suppression,
    validate_rate_columns,
    validate_row_counts,
    validate_stage2_denominators,
    validate_state_uniqueness,
)

logger = logging.getLogger(__name__)


def _write_data_dictionary() -> None:
    text = f"""# BarrierLens Dashboard — Data Dictionary

Generated by `scripts/build_dashboard_datasets.py`.

## woman_level_master.csv
| Column | Description |
|--------|-------------|
| woman_index | 0-based row index aligned to Stage 1/2 pipeline |
| caseid | NFHS case identifier (when present in raw extract) |
| state_name | Human-readable state/UT from v024 |
| residence | Urban / Rural from v025 |
| wealth_quintile | NFHS wealth quintile label |
| wealth_tier | Poor / Middle / Rich (for demographic panels) |
| education_tier | No Education / Primary / Secondary / Higher |
| caste_group | Simplified caste/tribe category |
| religion | Religion label from v130 |
| occupation_group | Occupation category from v717 |
| observed_household / observed_logistic / observed_facility | Stage 1 binary targets (Rail A) |
| pred_household_prob / pred_logistic_prob / pred_facility_prob | OOF Stage 1 probabilities (Rail B) |
| composite_barrier_score | Mean of three OOF barrier probabilities |
| cluster_id | K-Means cluster assignment |
| archetype_name | Named risk archetype |
| observed_target_unmet_fp / observed_target_anc_gap | Stage 2 targets (NaN outside analytic sample) |
| pred_target_unmet_fp_prob / pred_target_anc_gap_prob | Stage 2 XGBoost predicted probabilities |

## state_level_summary.csv
One row per state/UT. Includes mean observed and OOF-predicted rates for each barrier type,
cluster shares, and Stage 2 outcome metrics with restricted-sample Ns.

## state_barrier_long.csv
Long format: state × barrier_type — optimised for Power BI choropleth toggles.

## demographic_summary.csv
Grouped by wealth_tier × education_tier × residence × caste_group × barrier_type.
Cells with N < {MIN_CELL_N} have `suppress_flag=True` and null rates.

## cluster_summary.csv
One row per cluster with archetype name, size, share, and mean feature profile.

## cluster_state_distribution.csv
Cluster × state counts and within-cluster shares for stacked bar charts.
"""
    DATA_DICTIONARY_OUTPUT.write_text(text, encoding="utf-8")
    logger.info("Saved data dictionary -> %s", DATA_DICTIONARY_OUTPUT)


def run_dashboard_pipeline(output_dir: Path | None = None) -> Dict[str, pd.DataFrame]:
    """Build master dataset, aggregates, validate, and save all dashboard CSVs."""
    out_dir = Path(output_dir or DASHBOARD_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)

    report = ValidationReport()
    master, profiles = build_master_dataset()

    validate_row_counts(master, report)
    validate_cluster_coverage(master, report)
    validate_stage2_denominators(master, report)

    rate_cols = [
        "observed_household",
        "observed_logistic",
        "observed_facility",
        *PRED_COLS.values(),
        "composite_barrier_score",
    ]
    validate_rate_columns(master, rate_cols, report)

    state_summary = build_state_level_summary(master)
    state_long = build_state_barrier_long(state_summary)
    demo_summary = build_demographic_summary(master)
    cluster_summary = build_cluster_summary(master, profiles)
    cluster_state = build_cluster_state_distribution(master)

    validate_state_uniqueness(state_summary, report)
    validate_rate_columns(
        state_summary,
        [c for c in state_summary.columns if "rate" in c or "prob" in c or "score" in c],
        report,
    )
    validate_demographic_suppression(demo_summary, report)

    save_master_dataset(master, out_dir / MASTER_OUTPUT.name)
    state_summary.to_csv(out_dir / STATE_SUMMARY_OUTPUT.name, index=False)
    state_long.to_csv(out_dir / STATE_BARRIER_LONG_OUTPUT.name, index=False)
    demo_summary.to_csv(out_dir / DEMO_SUMMARY_OUTPUT.name, index=False)
    cluster_summary.to_csv(out_dir / CLUSTER_SUMMARY_OUTPUT.name, index=False)
    cluster_state.to_csv(out_dir / CLUSTER_STATE_OUTPUT.name, index=False)

    report.save_json(out_dir / VALIDATION_REPORT_OUTPUT.name)
    _write_data_dictionary()

    logger.info(
        "Dashboard pipeline complete. Validation passed=%s (%d warnings)",
        report.to_dict()["passed"],
        len(report.warnings),
    )

    if report.errors:
        for err in report.errors:
            logger.error("Validation error: %s", err)
        raise RuntimeError(f"Dashboard validation failed: {report.errors}")

    return {
        "master": master,
        "state_summary": state_summary,
        "state_barrier_long": state_long,
        "demographic_summary": demo_summary,
        "cluster_summary": cluster_summary,
        "cluster_state_distribution": cluster_state,
        "validation_report": report.to_dict(),
    }


def configure_logging(level: int = logging.INFO) -> None:
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    )
